spring:
  application:
    name: car_management
  datasource:
    url: jdbc:mariadb://localhost:3306/facenet_car
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
app:
  upload-dir: C:/Users/ngman/Downloads/car_management/src/main/resources/static/
server:
  port: 8089